### ISSUE TITLE
Add requirements.txt file for all needed Python Libraries

### ISSUE THREAD

**Issue by alisonlhart** [IBM/turbonomic_eda#1]
For ansible-builder, the collection should have a requirements.txt file with all Python libraries the collection needs. The README states that the awscli library is required, so this should be added to the requirements.txt file, along with any other needed Python libraries (if applicable). 

Any binary dependencies should be placed in a bindep.txt file, also for the consumption of ansible-builder.

This will allow the turbonomic_eda collection to be used inside of Execution Environments. 

[Ansible Builder metadata docs](https://ansible.readthedocs.io/projects/builder/en/stable/collection_metadata/)

These files must be included in the final build and release to Galaxy and Automation Hub for Ansible Builder to operate correctly.

Please include this in the next release, and feel free to email ansiblepartners@redhat.com with any questions.

**Comment by rayrayibm** [comment]
Commit 11a5a03 resolves this issue.
