### ISSUE TITLE
EDA plugins should be under extensions/eda/plugins/event_source 

### ISSUE THREAD

**Issue by alisonlhart** [IBM/turbonomic_eda#4]
EDA structure requires event_source and event_filter plugins to be under an `extensions/eda/plugins/event_source` or `extensions/eda/plugins/event_filter` directory respectively. The collection's EDA plugin is currently located under `plugins/modules/eda_webhook.py`. 

Please refactor the collection into this structure, as the Red Hat Ansible EDA controller expects it to be in this location. 

**Note - for certification on [Automation Hub](https://console.redhat.com/ansible/automation-hub/):**

This may result in new test failures, since existing test tooling does not evaluate under the extensions/ directory and there is a separate test process for this content. This is subject to change in the future, but currently we use the common python testing tool tox to perform static code analysis with a set of linters.

The linters used for EDA are: pylint, darglint, and ruff. These linters run specifically over the /extensions/eda/plugins dir or deeper. We have built a tox template you can plug into your CI to mimic the tests on Automation Hub. We highly recommend using this template, as some of these linter tests have been deemed irrelevant for certification and are skipped. The link to the templates and documentation is here: https://github.com/ansible/eda-partner-testing

There is additional documentation on the EDA content creation process here: https://redhat-connect.gitbook.io/ansible-eda-content-creation-workflow-guide/

**Comment by rayrayibm** [comment]
@alisonlhart the `plugins/modules/eda_webhook.py` module is not an EDA event source or event filter module.  It is an action module that can be used to create the webhook within Turbonomic that would forward events to Event Driven Ansible.  Unless I'm missing something, no change to it's location needs to be made.

**Comment by alisonlhart** [comment]
To clarify for my understanding - this action plugin is not the webhook itself, but the method for users to build their own?

**Comment by rayrayibm** [comment]
That is correct, the plugin gives users a method to create the webhook via ansible.

**Comment by alisonlhart** [comment]
Makes sense! In that case, this issue and #5 aren't needed, unless a future event source/filter plugin is added. Feel free to close the other one out!
